volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:latest
    ports:
     - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env

  app:
    build:
      context: ./referral_system
      dockerfile: Dockerfile
    restart: always
    ports:
     - 8000:8000
    env_file: .env
    volumes:
      - static:/backend_static/static/
    depends_on:
      - db


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - app